---
- name: Collect the list of VMs
  virt:
    command: list_vms
  register: all_vms

- name: Collect info on each VM
  virt:
    name: "{{ item }}"
    command: get_xml
  loop: "{{ all_vms.list_vms }}"
  register: all_vms_xml

- name: Create temporary file
  delegate_to: localhost
  tempfile:
    state: file
    suffix: temp
  register: hosts_xml_file

- name: Generate input file
  delegate_to: localhost
  template: src=hosts.xml.j2 dest="{{ hosts_xml_file.path }}"

- name: Tell infragit about results
  delegate_to: localhost
  debug: msg=":>:> libvirt {{ hosts_xml_file.path }} <:<:"

- name: Create temporary file
  delegate_to: localhost
  tempfile:
    state: file
    suffix: temp
  register: arp_table_file

- name: Dump the arp table
  command: ip neigh
  register: arp_table_output

- name: copy the output to a local file
  copy:
    content: "{{ arp_table_output.stdout }}"
    dest: "{{ arp_table_file.path }}"
  delegate_to: localhost

- name: Tell infragit about results
  delegate_to: localhost
  debug: msg=":>:> arp {{ arp_table_file.path }} <:<:"
